#!/bin/bash -l
#SBATCH -p regular 					# change this option for non-debug runs
#SBATCH -t 00:20:00					# adjust the amount of time as necessary
#SBATCH -A mp309
#SBATCH -o auto-openmp24.%j.stdout
#SBATCH -e auto-openmp24.%j.error
#SBATCH -N 1						# you'll never need more than 1 node for the serial code

rm openmp.txt
srun -n 1 -c 1 ./serial -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=1
srun -n 1 -c 1 ./openmp -p 1 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp -p 2 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp -p 4 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=6
srun -n 1 -c 6 ./openmp -p 6 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=12
srun -n 1 -c 12 ./openmp -p 12 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=18
srun -n 1 -c 18 ./openmp -p 18 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=24
srun -n 1 -c 24 ./openmp -p 24 -n 50000 -no -s openmp.txt
export OMP_NUM_THREADS=2
srun -n 1 -c 2 ./openmp -p 2 -n 100000 -no -s openmp.txt
export OMP_NUM_THREADS=4
srun -n 1 -c 4 ./openmp -p 4 -n 200000 -no -s openmp.txt
export OMP_NUM_THREADS=6
srun -n 1 -c 6 ./openmp -p 6 -n 300000 -no -s openmp.txt
export OMP_NUM_THREADS=12
srun -n 1 -c 12 ./openmp -p 12 -n 600000 -no -s openmp.txt
export OMP_NUM_THREADS=18
srun -n 1 -c 18 ./openmp -p 18 -n 900000 -no -s openmp.txt
export OMP_NUM_THREADS=24
srun -n 1 -c 24 ./openmp -p 24 -n 1200000 -no -s openmp.txt
./autograder -v openmp -s openmp.txt
