#!/bin/bash -l
#SBATCH -p debug 		# change this option for non-debug runs
#SBATCH -t 00:10:00		# adjust the amount of time as necessary
#SBATCH -A mp309
#SBATCH -o openmp24.%j.stdout
#SBATCH -e openmp24.%j.error
#SBATCH -N 1			# you'll never need more than 1 node for the openmp code

export OMP_NUM_THREADS=24
srun -n 1 -c 24 ./openmp -n 500 -o openmp.txt