#!/bin/bash -l
#SBATCH -p debug 		# change this option for non-debug runs
#SBATCH -t 00:10:00		# adjust the amount of time as necessary
#SBATCH -A mp309
#SBATCH -o serial.%j.stdout
#SBATCH -e serial.%j.error
#SBATCH -N 1			# you'll never need more than 1 node for the serial code

srun -n 1 -c 1 ./serial -n 500 -o serial.txt