#!/bin/bash -l
#SBATCH -p debug 		# change this option for non-debug runs
#SBATCH -t 00:10:00		# adjust the amount of time as necessary
#SBATCH -N 24 			# adjust the number of nodes per test (e.g. start with 1, 2, ...)
#SBATCH -A mp309
#SBATCH -o mpi24.%j.stdout
#SBATCH -e mpi24.%j.error

srun -n 24 ./mpi -n 500 -o mpi.txt  # adjust -n here as well